create table factura_rips_json (
	factura varchar (20),
	tiporips varchar (2),
	concepto varchar (4),
	servicio varchar (15),
	codPrestador varchar (12),
	fechalnicioAtencion timestamp,
	numAutorizacion varchar (30),
	codConsulta varchar (6),
	modalidadGrupoServicioTecSal varchar (2),
	grupoServicios varchar (2),
	codServicio int,
	finalidadTecnologiaSalud  varchar (2),
	causaMotivoAtencion  varchar (2),
	codDiagnosticoPrincipal varchar (25),
	codDiagnosticoRelacionadol varchar (25),
	codDiagnosticoRelacionado2 varchar (25),
	codDiagnosticoRelacionado3 varchar (25),
	tipoDiagnosficoPrincipal varchar (2),
	tipoOocumentoldentificacion varchar (2),
	numDocumentoldentificacion varchar (20),
	vrServicio int,
	conceptoRecaudo varchar (2),
	valorPagoModeradOr int,
	numFEVPagoModerador varchar (20),
	consecutivo int,
	idMIPRES varchar (15),
	codProcedimiento varchar (6),
	viaIngresoServicioSalud varchar (2),
	finafidadTecnologiaSalud varchar (2),
	tipoDocumentoldentificacion varchar (2),
	codDiagnosficoPrincipal varchar (25),
	codDiagnosticoRelacionado varchar (25),
	codComplicacion varchar (25),
	fechaDispensAdmon timestamp,
	tipoMedicamento varchar (2),
	codTecnologiaSalud varchar (20),
	nomTecnologiaSalud varchar (30),
	concentracionMedicamento int,
	unidadMedida int,
	forrnaFarrnaceutica VARCHAR (8),
	unidadMinDispensa int,
	cantidadMedicamento int,
	diasTratamiento int,
	vrUnitMedicamento int,
	fechaSuministroTecnologia timestamp,
	tipoOS varchar (2),
	cantidadOS int,
	vrUnitOS int,
)